Cluster manager
LeszekBlazewski/lab-229-cluster pull request #7
Opened 2021-11-23 22:23 UTC by damiankoper

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

- fixes #

**Additional information**

2021-11-27 13:36 UTC, LeszekBlazewski requested changes
Damian, as always great job. I am amazed by your ability to write clean code, still follow best practices and do it in such short time!

I hope you don't mind the Docker focused code review but I also looked through the backend and frontend and as always ... you are the boss there and I like your codestyle therefore I trust you 🙂 

I didn't fully verify my concepts but they should work in most cases. If they don't please let me know. If you have any questions/need help, please ping me!

Nice one 🚀 !

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/docker-compose.yaml
> +      192.168.0.141 --ssh-key /keys/id_ed25519 --ssh-auth publickey,password"
This is bad. Please disable password auth.

We want to have this as configurable as it gets. What I would probably make is a custom wetty image based on wettyoss/wetty which has inside only ENV variables defined and will use them for the command. What I mean by that is smth like this:

```Dockerfile
FROM wettyoss/wetty

# here all the necessary env variables (You can provide some default values here if you want but they will be also in compose since we have everything inside compose)
ENV SSH_USER

CMD wetty -p $PORT ....  --ssh-user $SSH_USER .... (Please validate this, you cant use plain CMD [ ] since we need shell variables, maybe it would be better to use CMD [ "bash", "-c", "wetty -p $PORT ..." ] but plain CMD should work :)

And in docker compose, simply build our image and let it run our custom command.

```yaml
wetty:
    build:
      context: .
      dockerfile: WettyDockerfile
```

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/Dockerfile
> +COPY --from=build /app/packages/api/dist ./dist
Good stuff!

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/src/app.service.ts
> +        createProxyMiddleware('/api/wetty', {
Move this to env variable for supper modular setup as with other envs

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/src/nodes/interfaces/Inventory.interface.ts
> +}
Nice one

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/src/nodes/nodes.controller.ts
> +  @Cron('*/10 * * * * *')
Can we make this configurable? ENV variable please?

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/src/nodes/nodes.controller.ts
> +  @Get('check-states')
Thanks for that endpoint from all of the impatient users!

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/src/nodes/nodes.service.ts
> +    this.logger.log(`[Node ${address}] GRUB boot with: ${bootOS}`);
Thanks for logging my man, will be useful!

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/api/test/data/inventory.yml
> +        #   name: Node 04
Whoops yaml link filed again.

Can we please remove the commented out part? (or indent it :P)

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/front/components/layout/GlobalFooter.vue
> +      >
Thanks for including us in this lovely project!

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/front/components/nodes/NodesCard.vue
> +  <!-- TODO: vuetify-confirm on {boot, shutdown} -->
Still something TODO or we abandon this?

2021-11-27 13:36 UTC, LeszekBlazewski commented on manager/packages/front/pages/app/terminal.vue
> +    }
Hell yeah, nice hacking 🚀

2021-11-27 13:39 UTC, damiankoper commented on manager/Dockerfile
> +COPY --from=front-production /app/packages/front /app/packages/front
So it's file

2021-11-27 14:28 UTC, damiankoper commented on manager/docker-compose.yaml
> +      - BASE_URL_SOCKET=http://localhost:7000/
This is used in the front SPA app from the user's perspective. This should be the object of further config when the master URL is known.

2021-11-27 14:29 UTC, damiankoper commented on manager/docker-compose.yaml
> +      - BASE_URL_SOCKET=http://localhost:7000/
I think we do not need to specify this URL anymore since we have the same origin.

2021-11-27 14:31 UTC, damiankoper commented on manager/Dockerfile.base
> +COPY ./lerna.json ./
In fact, these deps were needed for wetty installed locally. Since I've used an external image these are not needed anymore.

2021-11-27 14:42 UTC, damiankoper commented on manager/docker-compose.yaml
> +      - 3001
This is not the case. Browser does not make SSH connection. It connects to wetty's backend via WebSockets and then Wetty makes connection to master.

2021-11-27 14:43 UTC, damiankoper commented on manager/docker-compose.yaml
> +      - 3001
I've already removed this mapping since this port was used as a wetty's frontend<->backend communication and was accessed internally by API service via our proxy.

2021-11-27 14:49 UTC, damiankoper commented on manager/docker-compose.yaml
> +      192.168.0.141 --ssh-key /keys/id_ed25519 --ssh-auth publickey,password"
This is line from wetty help
`  --ssh-auth      defaults to "password", you can use "publickey,password"`
It looks like we have to fallback to password.

Can I use interpolation directly in the `command: ` instead of making custom image?

2021-11-28 19:00 UTC, damiankoper commented on manager/docker-compose.yaml
> +      - WETTY_URL=http://wetty:3001/
I've moved to env all variables that matter in terms of the config of external dependencies e.g. boot options, TFTP port, ssh etc.
Variable like `WETTY_URL` (or `WETTY_TARGET_URL` after changes) configures container to container communication inside the same stack and shouldn't be an object of further changes thus these were not interpolated from env.

2021-11-28 23:19 UTC, LeszekBlazewski commented on manager/packages/api/src/nodes/nodes.controller.ts
> +  @Cron(`*/${process.env.STATE_CHCEK_INTERVAL || 10} * * * * *`)
Small typo :(

2021-11-28 23:19 UTC, LeszekBlazewski commented on manager/docker-compose.yaml
> +      - WETTY_URL=http://wetty:3001/
This is exactly what I meant. Thanks!

2021-11-28 23:20 UTC, LeszekBlazewski commented on manager/Dockerfile.base
> +COPY ./lerna.json ./
Awesome, thanks for clearing this

2021-11-28 23:21 UTC, LeszekBlazewski commented on manager/docker-compose.yaml
> +      - BASE_URL_SOCKET=http://localhost:7000/
Yeah, nice one, thanks for moving this to relative paths

2021-11-28 23:23 UTC, LeszekBlazewski commented on manager/docker-compose.yaml
> +      - 3001
Ok, I understand now. Nice that we don't have this exposed. I am happy with what we have now :)

2021-11-28 23:29 UTC, LeszekBlazewski commented on manager/docker-compose.yaml
> +      192.168.0.141 --ssh-key /keys/id_ed25519 --ssh-auth publickey,password"
Ok, I see, then let's leave publickey,password. Password auth will be blocked anyway by ubuntu config so it is fine.

I wanted custom Dockerfile because I though we might want to run this as standalone container but in such case it can also be run with Docker-compose. It's fine. We can stick to interpolation.

2021-11-28 23:32 UTC, LeszekBlazewski approved these changes
Thanks for fixes Damiano!

2021-11-28 23:32 UTC, LeszekBlazewski commented on manager/packages/front/store/nodesStore.ts
> +      console.log(this);
To be removed right?

2021-11-28 23:35 UTC, merged